base_url: "https://app.credissuer.com"
email: "testissuer13@gmail.com"
password: "password@123"
csrf_token: "Da1J0MrehnX40T9aqeRiSe86uvZS1bz9KXNXsD8dgaFWup1RoKy3nkjguEtLKJ9w"
credential_template: "472BB9984C09"
recipient_info:
  data:
    recipientFirstName: "Gowtham"
    recipientLastName: "Panyam"
    recipientEmail: "chandru.s@ooru.io"
    recipientPhone: "9999999999"
